### PR TITLE
reversed the expected and actual values in knapsack test suite

### PR DESCRIPTION
**Pull request by markstanden**
JUnit requires expected value as first argument.

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Yes, that's correct. Thanks!

**Comment by SleeplessByte** [comment]
Would you be so kind to rebase this on main?

**Comment by markstanden** [comment]
Hi Sleepless, this is done (I think...)

**Comment by markstanden** [comment]
Do I need to do anything further to have this merged?

**Comment by SleeplessByte** [comment]
Nope! Pinging me works 🗡️ 😄

**Pull request merged**
