### PR TITLE
For #340. Use Gradle Kotlin DSL for all exercises.

### PR DESCRIPTION
**Pull request by dector**
Changes:
  - Using Gradle Kotlin DSL.
  - Updated gradle to `6.0.1`.
  - Updated Kotlin to `1.3.60`.
  - Added missing gradle wrapper files to template.

### CODE REVIEW

**Comment by dector** [comment]
> Impossible to review 347 files.

There is no need to review them. I tried to make each commit self-scoped (kinda).

At first, I've [updated template](https://github.com/exercism/kotlin/pull/358/commits/bb7047d65bb70bd81a8ce41dc924b514bfbfb166).
Then showed how this effects [single exercises (hello-world)](https://github.com/exercism/kotlin/pull/358/commits/12379b4109c64f4c41d0ff9bcdd7070799f2259c).
Then copied all gradle files from template to [all exercises](https://github.com/exercism/kotlin/pull/358/commits/7aa94244edc26cfaecd81a80241278642be2f143).

[Here are](https://github.com/exercism/kotlin/pull/358/commits/ce57c8016bcea40f3e6ba471c1b6a3c612d842a7) some useful scripts.

The latest commit has fixes to `journey test scripts` as it's keep failing. :(

> build.gradle is not removed

Thanks for noticing this. It should be removed by script. My bad.

> The only thing troubles me, that I cannot compose 347 of 2+1+6+5*k, where k is natural.

Brilliant. :smile:

> And, just for the record, why build.gradles survived?

It contains quite tricky implementation to run tests against reference implementation. I want to rework this as a separate issue.

**Comment by eparovyshnaya** [comment]
I got the flow of commits, I have, truely. 

It actually helped me with the numbers. 

The thing I did not pay attention to is that `hellow world` lost it's `build.gradle`, and the rest of the exercises did not.  

And auxiliary scripts - two files more I missed. 

Thus 347 should be equal to
 - 2 handy scripts
 - 1 readme
 - 6 files in `_template`
 - 2 ci scripts
 - 6 files for `hellow world`
 - and 5 file for the rest of exercices. 

Hooray, it can be solved in N :)

Another thing bothers me now:  `build.gradle` is absent for `hellow world` and present in all the other packs.

**Comment by dector** [comment]
Moving fast and breaking things. :new_moon_with_face: 

Removed legacy `build.gradle` files for exercises.

Attention required for 4e6a37f8afa94e7bb71eee67daf7a8add26bf1ab.
Fixed (changed) `BankAccountTest`. Using thread pool executor instead of coroutines there. Decreases number of desired threads (single test is running > 2 minutes). Probably we should find a better way to test concurrency.

**Comment by eparovyshnaya** [comment]
>  Use custom thread pool in `BankAccount` exercise 
Oh, dear. That was unexpected here. Looks good. 

> Moving fast and breaking things
It's totally normal and absolutely welcome.

**Comment by dector** [comment]
> Oh, dear. That was unexpected here.

**Comment by dector** [comment]
@eparovyshnaya Fixed another one test in latest commit.

**Comment by dector** [comment]
33 mins for journey test. :fearful:  I guess it's because of cold start. :)

**Comment by eparovyshnaya** [comment]
@dector 
btw, can we totally avoid all this build infrastructure replication for all exercises *in the repo*?

I suppose this PR and surrounding activity is dedicated to brushing, while keeping status quo.

But stepping a bit further, we can add a simple *task* to the root build script that will copy *_template*-ed wrapper and build scripts in each exercise folder *at build time*. This simple step will preent us from
 - unexpected dependencies (like the ones we faced the other day on this PR)
 - necessity of wordy dublicated updates
 - attention spreading on build-system related prs review )

You've delt with our build system already. How do you think, is this feasible?

**Pull request merged**
