### PR TITLE
Updating gradle version from 8.4 to 8.6

### PR DESCRIPTION
**Pull request by MahmoudN288**
Updating gradle version from 8.4 to 8.6

### CODE REVIEW

**Comment by MahmoudN288** [comment]
@ErikSchierboom  If you are ready?

**Comment by ErikSchierboom** [comment]
Ci checks are failing. Could you please look into those?

**Comment by SleeplessByte** [comment]
@MahmoudN288 is this still something you want to work on?

**Comment by SleeplessByte** [comment]
I'm closing this so someone else can make an attempt. Feel free to ping me here if you decide to work on this after all!

**Pull request closed without merging**
