### PR TITLE
grains: add to track

### PR DESCRIPTION
**Pull request by stkent**
[problem specification directory](https://github.com/exercism/problem-specifications/tree/117d062a18124f7535124a50ff9bb7c6660aa4e7/exercises/grains).

This is foregone in the Java track, but I'm not sure why. I'll investigate porting it over to there.

I was thinking this should be estimated at a 4, but would like some feedback on that idea since I'm not sure how tricky others feel the concepts behind `BigInteger` are. Right now the exercise is unestimated and positioned at the end of the track.

### CODE REVIEW

**Comment by stkent** [comment]
I found this context from the very beginning of the Java track:

https://github.com/exercism/java/issues/3#issue-28507735

It's not clear to me:

1. Why sourcing from Java Ranch means those exercises may not be implemented on the Java track, or
2. Whether that same reasoning would prevent implementation of those exercises on the Kotlin track.

cc @kytrinyx, these seem like things you are likely to know :o)

**Comment by kytrinyx** [comment]
I made that call early on because the JavaRanch is in Java, and I didn't want to be in competition with them. It would not affect any other tracks (they only have Java).

It might be a complete non-issue, though. I'll make a note to ask Paul who started the CattleDrive.

**Comment by stkent** [comment]
Roger that, thanks for the context! Seems like we're good to go with this in the Kotlin track then :)

**Comment by sdavids13** [comment]
Yea, difficulty somewhere in 3-4 range seems reasonable. This looks good to me.

**Comment by stkent** [comment]
Added difficulty and positioning.

**Comment by stkent** [comment]
@kytrinyx following up on https://github.com/exercism/kotlin/pull/74#issuecomment-310568486; any news on this front?

**Comment by kytrinyx** [comment]
Sorry, I've not gotten to this one yet.

**Comment by stkent** [comment]
No worries; I'll check in again at some time TBD in the future :)

**Comment by kytrinyx** [comment]
Much appreciated 💖

**Pull request merged**
