### PR TITLE
Add a gradle wrapper for each exercise so users don't need to install gradle

### LINKED ISSUE #234: Add gradle wrapper to each exercise
This way folks don't need to have gradle installed to get started.

Grab the exercise, run gradlew test and go. :-)

### PR DESCRIPTION
**Pull request by mdowds**
Fixes #234.

This is my first PR so let me know if there's something I've missed!

### CODE REVIEW

**Comment by mikegehard** [comment]
Thanks for doing this! Makes it easier to get started more quickly.

Is there anything holding up getting in merged in?

**Comment by mdowds** [comment]
No problem! There's nothing that I'm aware of.

**Comment by mikegehard** [comment]
Closes https://github.com/exercism/kotlin/issues/234

**Comment by mikegehard** [comment]
Thank you!

**Pull request merged**
